---
apiVersion: v2
name: hive
version: 1.0.0
description: Deploy hive
home: https://docs.graphql-hive.com/self-hosting/get-started
dependencies:
  - name: hive-app
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: clickhouse
    version: 1.0.3
    repository: https://charts.bitnami.com/bitnami
  - name: hive-emails
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: kafka
    version: 19.1.3
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
  - name: hive-schema
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: hive-server
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: hive-storage
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: supertokens
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: hive-tokens
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: hive-usage
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: hive-usage-ingestor
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
  - name: hive-webhooks
    version: 1.0.0
    repository: https://registry.dblc.io/chartrepo/diabolocom
