global:
  image:
    tag: 59b64c36c866b3555c135c70de76a884e63f8619
  app_base_url: base.url.io
  clickhouse_username: default
  postgresql:
    auth:
      database: engage-hive
      user: postgres
  apiKey:
    key: "yourApiKey"
  encryption_secret: yourEncryptionSecret
  email:
    provider: sendmail
    from: no-reply@yourDomain.com

clickhouse:
  fullnameOverride: clickhouse
  zookeeper:
    fullnameOverride: clickhouse-zookeeper

kafka:
  fullnameOverride: kafka
  zookeeper:
    fullnameOverride: kafka-zookeeper
  minBrokerId: 1

postgresql:
  fullnameOverride: postgres-postgresql

redis:
  fullnameOverride: redis

supertokens:
  fullnameOverride: supertokens

ingress:
  use_secure_protocol: "false"
