global:
  image:
    tag: 59b64c36c866b3555c135c70de76a884e63f8619
  clickhouse_username: default
  postgresql:
    auth:
      database: engage-hive
      user: postgres

image:
  name: ghcr.io/kamilkisiela/graphql-hive/storage
  pullPolicy: Always

server_port: 8080
app_name: hive-storage

migrator: up
clickhouse_migrator: up

postgres_host: postgres-postgresql
postgres_port: 5432

clickhouse_protocol: http
clickhouse_host: clickhouse
clickhouse_port: 8123

sentry_dns: ''
sentry_enabled: 0
