global:
  image:
    tag: 59b64c36c866b3555c135c70de76a884e63f8619
  clickhouseUsername: default
  postgresql:
    auth:
      database: graphql-hive
      user: postgres

image:
  name: ghcr.io/kamilkisiela/graphql-hive/storage
  pullPolicy: Always

serverPort: 8080
appName: hive-storage

migrator: up
clickhouseMigrator: up

postgresHost: postgres-postgresql
postgresPort: 5432

clickhouseProtocol: http
clickhouseHost: clickhouse
clickhousePort: 8123

sentryDns: ''
sentryEnabled: 0
