{{- $url := printf "%s" .Values.global.appBaseUrl }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.namespace }}-root-ingress
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    {{ if eq .Values.ingress.useSecureProtocol "true" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{ else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-cookie-path: |
      / "/; HTTPOnly; Secure; SameSite=strict"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: upgrade-insecure-requests";
    {{ end }}
spec:
  ingressClassName: private
  rules:
    - host: {{ $url }}
      http:
        paths:
          - backend:
              service:
                name: app-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: server-svc
                port:
                  number: 80
            path: /graphql
            pathType: Prefix
