---

apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-env-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
data:
  MIGRATOR: {{ .Values.migrator }}
  CLICKHOUSE_MIGRATOR: {{ .Values.clickhouseMigrator }}
  POSTGRES_HOST: {{ .Values.postgresHost }}
  POSTGRES_PORT: "{{ .Values.postgresPort }}"
  POSTGRES_DB: {{ .Values.global.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.global.postgresql.auth.user }}
  CLICKHOUSE_PROTOCOL: {{ .Values.clickhouseProtocol }}
  CLICKHOUSE_HOST: {{ .Values.clickhouseHost }}
  CLICKHOUSE_PORT: "{{ .Values.clickhousePort }}"
  CLICKHOUSE_USERNAME: {{ .Values.global.clickhouseUsername }}
  SENTRY_DNS: "{{ .Values.sentryDns }}"
  SENTRY_ENABLED: "{{ .Values.sentryEnabled }}"
