---

apiVersion: v1
kind: ConfigMap
metadata:
  name: usage-env-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
data:
  NODE_ENV: '{{ .Values.nodeEnv }}'
  PORT: '{{ .Values.serverPort }}'
  TOKENS_ENDPOINT: '{{ .Values.tokensEndpoint }}'
  KAFKA_CONNECTION_MODE: '{{ .Values.kafkaConnectionMode }}'
  KAFKA_TOPIC: '{{ .Values.kafkaTopic }}'
  KAFKA_BROKER: '{{ .Values.kafkaBroker }}'
  KAFKA_BUFFER_SIZE: '{{ .Values.kafkaBufferSize }}'
  KAFKA_BUFFER_INTERVAL: '{{ .Values.kafkaBufferInterval }}'
  KAFKA_BUFFER_DYNAMIC: '{{ .Values.kafkaBufferDynamic }}'

  SENTRY: '{{ .Values.sentry }}'
  SENTRY_DSN: '{{ .Values.sentryDsn }}'

  PROMETHEUS_METRICS: '{{ .Values.prometheusMetrics }}'
  PROMETHEUS_METRICS_LABEL_INSTANCE: '{{ .Values.prometheusMetricsLabelInstance }}'