---

apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-env-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
data:
  NODE_ENV: '{{ .Values.nodeEnv }}'
  PORT: '{{ .Values.serverPort }}'

  REDIS_HOST: '{{ .Values.redisHost }}'
  REDIS_PORT: '{{ .Values.redisPort }}'

  SENTRY: '{{ .Values.sentry }}'
  SENTRY_DSN: '{{ .Values.sentryDsn }}'

  PROMETHEUS_METRICS: '{{ .Values.prometheusMetrics }}'
  PROMETHEUS_METRICS_LABEL_INSTANCE: '{{ .Values.prometheusMetricsLabelInstance }}'

  REQUEST_BROKER: '{{ .Values.requestBroker }}'
  REQUEST_BROKER_ENDPOINT: '{{ .Values.requestBrokerEndpoint }}'
  REQUEST_BROKER_SIGNATURE: '{{ .Values.requestBrokerSignature }}'
