---
{{- $appBaseUrl := printf "http://%s" .Values.global.appBaseUrl }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
data:
  NODE_ENV: '{{ .Values.nodeEnv }}'
  PORT: '{{ .Values.serverPort }}'
  APP_BASE_URL: '{{ $appBaseUrl }}'
  SUPERTOKENS_CONNECTION_URI: '{{ .Values.supertokensConnectionUri }}'
  SUPERTOKENS_API_KEY: '{{ .Values.global.apiKey.key }}'
  EMAILS_ENDPOINT: '{{ .Values.emailsEndpoint }}'
  GRAPHQL_ENDPOINT: '{{ .Values.graphqlEndpoint }}'
  SERVER_ENDPOINT: '{{ .Values.serverEndpoint }}'
  AUTH_REQUIRE_EMAIL_VERIFICATION: '{{ .Values.authRequireEmailVerification }}'
