---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-tokens-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hive
      service: {{ .Values.appName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: hive
        service: {{ .Values.appName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: '{{ .Values.image.name }}:{{ .Values.global.image.tag }}'
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          envFrom:
            - configMapRef:
                name: tokens-env-cm
          env:
            - name: APP_INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          ports:
            - containerPort: {{ .Values.serverPort }}
