---

apiVersion: v1
kind: ConfigMap
metadata:
  name: server-env-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
data:
  NODE_ENV: '{{ .Values.nodeEnv }}'
  PORT: '{{ .Values.serverPort }}'

  POSTGRES_HOST: '{{ .Values.postgresHost }}'
  POSTGRES_PORT: '{{ .Values.postgresPort }}'
  POSTGRES_DB: '{{ .Values.global.postgresql.auth.database }}'
  POSTGRES_USER: '{{ .Values.global.postgresql.auth.user }}'

  ROARR_LOG: '{{ .Values.roarrLog }}'

  CLICKHOUSE_PROTOCOL: '{{ .Values.clickhouseProtocol }}'
  CLICKHOUSE_HOST: '{{ .Values.clickhouseHost }}'
  CLICKHOUSE_PORT: '{{ .Values.clickhousePort }}'
  CLICKHOUSE_USERNAME: '{{ .Values.global.clickhouseUsername }}'

  REDIS_HOST: '{{ .Values.redisHost }}'
  REDIS_PORT: '{{ .Values.redisPort }}'

  TOKENS_ENDPOINT: '{{ .Values.tokensEndpoint }}'
  WEBHOOKS_ENDPOINT: '{{ .Values.webhooksEndpoint }}'
  SCHEMA_ENDPOINT: '{{ .Values.schemaEndpoint }}'
  EMAILS_ENDPOINT: '{{ .Values.emailsEndpoint }}'

  ENCRYPTION_SECRET: '{{ .Values.global.encryptionSecret }}'

  WEB_APP_URL: '{{ .Values.webAppUrl }}'

  SUPERTOKENS_CONNECTION_URI: '{{ .Values.supertokensConnectionUri }}'
  SUPERTOKENS_API_KEY: '{{ .Values.global.apiKey.key }}'

  INTEGRATION_GITHUB: '{{ .Values.integrationGithub }}'
  INTEGRATION_GITHUB_GITHUB_APP_ID: '{{ .Values.integrationGithubGithubAppId }}'
  INTEGRATION_GITHUB_GITHUB_APP_PRIVATE_KEY: '{{ .Values.integrationGithubGithubAppPrivateKey }}'

  AUTH_ORGANIZATION_OIDC: '{{ .Values.authOrganizationOidc }}'

  SENTRY: '{{ .Values.sentry }}'
  SENTRY_DSN: '{{ .Values.sentryDsn }}'

  PROMETHEUS_METRICS: '{{ .Values.prometheusMetrics }}'
  PROMETHEUS_METRICS_LABEL_INSTANCE: '{{ .Values.prometheusMetricsLabelInstance }}'

  RATE_LIMIT_ENDPOINT: '{{ .Values.rateLimitEndpoint }}'
