---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-emails-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.app_name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hive
      service: {{ .Values.app_name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: hive
        service: {{ .Values.app_name }}
        release: {{ .Release.Name }}
    spec:
{{- if gt (int .Values.replicaCount) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.app_name }}
                  - key: release
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
{{- end }}
      containers:
        - name: {{ .Values.app_name }}
          image: "{{ .Values.image.name }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          envFrom:
            - configMapRef:
                name: emails-env-cm
          env:
            - name: APP_INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          ports:
            - containerPort: {{ .Values.server_port }}
