---

apiVersion: v1
kind: ConfigMap
metadata:
  name: emails-env-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
data:
  NODE_ENV: '{{ .Values.nodeEnv }}'
  PORT: '{{ .Values.serverPort }}'
  REDIS_HOST: '{{ .Values.redisHost }}'
  REDIS_PORT: '{{ .Values.redisPort }}'
  BULLMQ_COMMANDS_FROM_ROOT: '{{ .Values.bullmqCommandsFromRoot }}'
  EMAIL_FROM: '{{ .Values.global.email.from }}'
  EMAIL_PROVIDER: '{{ .Values.global.email.provider }}'
  EMAIL_PROVIDER_SMTP_PROTOCOL: '{{ .Values.emailProviderSmtpProtocol }}'
  EMAIL_PROVIDER_SMTP_HOST: '{{ .Values.emailProviderSmtpHost }}'
  EMAIL_PROVIDER_SMTP_PORT: '{{ .Values.emailProviderSmtpPort }}'
  EMAIL_PROVIDER_SMTP_AUTH_USERNAME: '{{ .Values.emailProviderSmtpAuthUsername }}'
  EMAIL_PROVIDER_SMTP_AUTH_PASSWORD: '{{ .Values.emailProviderSmtpAuthPassword }}'
  EMAIL_PROVIDER_POSTMARK_TOKEN: '{{ .Values.emailProviderPostmarkToken }}'
  EMAIL_PROVIDER_POSTMARK_MESSAGE_STREAM: '{{ .Values.emailProviderPostmarkMessageStream }}'
  EMAIL_PROVIDER_SMTP_REJECT_UNAUTHORIZED: '{{ .Values.emailProviderSmtpRejectUnauthorized }}'


  SENTRY: '{{ .Values.sentry }}'
  SENTRY_DSN: '{{ .Values.sentryDsn }}'

  PROMETHEUS_METRICS: '{{ .Values.prometheusMetrics }}'
  PROMETHEUS_METRICS_LABEL_INSTANCE: '{{ .Values.prometheusMetricsLabelInstance }}'

  RATE_LIMIT_ENDPOINT: '{{ .Values.rateLimitEndpoint }}'
