---
apiVersion: v1
kind: Service
metadata:
  name: emails-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}

spec:
  selector:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.serverPort }}
      protocol: TCP
      name: http-main
