---

apiVersion: v1
kind: ConfigMap
metadata:
  name: usage-ingestor-env-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive
    service: {{ .Values.appName }}
    release: {{ .Release.Name }}
data:
  NODE_ENV: '{{ .Values.nodeEnv }}'
  PORT: '{{ .Values.serverPort }}'
  KAFKA_CONNECTION_MODE: '{{ .Values.kafkaConnectionMode }}'
  KAFKA_BROKER: '{{ .Values.kafkaBroker }}'
  KAFKA_CONCURRENCY: '{{ .Values.kafkaConcurrency }}'
  KAFKA_CONSUMER_GROUP: '{{ .Values.kafkaConsumerGroup }}'
  KAFKA_TOPIC: '{{ .Values.kafkaTopic }}'
  CLICKHOUSE_PROTOCOL: '{{ .Values.clickhouseProtocol }}'
  CLICKHOUSE_HOST: '{{ .Values.clickhouseHost }}'
  CLICKHOUSE_PORT: '{{ .Values.clickhousePort }}'
  CLICKHOUSE_USERNAME: '{{ .Values.global.clickhouseUsername }}'

  HEARTBEAT_ENDPOINT: '{{ .Values.heartbeatEndpoint }}'

  SENTRY: '{{ .Values.sentry }}'
  SENTRY_DSN: '{{ .Values.sentryDsn }}'

  PROMETHEUS_METRICS: '{{ .Values.prometheusMetrics }}'
  PROMETHEUS_METRICS_LABEL_INSTANCE: '{{ .Values.prometheusMetricsLabelInstance }}'
