global:
  image:
    tag: 59b64c36c866b3555c135c70de76a884e63f8619
  clickhouseUsername: default

image:
  name: ghcr.io/kamilkisiela/graphql-hive/usage-ingestor
  pullPolicy: Always

appName: hive-usage-ingestor
serverPort: 8080
nodeEnv: production

kafkaConnectionMode: hosted
kafkaTopic: usage_reports_v2
kafkaConsumerGroup: usage-ingestor-v2
kafkaConcurrency: 1
kafkaBroker: kafka:9092

clickhouseProtocol: http
clickhouseHost: clickhouse
clickhousePort: 8123

replicaCount: 1

heartbeatEndpoint: ''

sentry: 0
sentryDsn: ''

prometheusMetrics: 0
prometheusMetricsLabelInstance: ''
