global:
  image:
    tag: 59b64c36c866b3555c135c70de76a884e63f8619

image:
  name: ghcr.io/kamilkisiela/graphql-hive/usage
  pullPolicy: Always

app_name: hive-usage
server_port: 8080
node_env: production

tokens_endpoint: http://tokens-svc:80

kafka_connection_mode: hosted
kafka_topic: usage_reports_v2
kafka_broker: kafka:9092
kafka_buffer_size: 350
kafka_buffer_interval: 1000
kafka_buffer_dynamic: 1

replicaCount: 1

sentry: 0
sentry_dsn: ''

prometheus_metrics: 0
prometheus_metrics_label_instance: ''
