global:
  image:
    tag: 59b64c36c866b3555c135c70de76a884e63f8619

image:
  name: ghcr.io/kamilkisiela/graphql-hive/usage
  pullPolicy: Always

appName: hive-usage
serverPort: 8080
nodeEnv: production

tokensEndpoint: http://tokens-svc:80

kafkaConnectionMode: hosted
kafkaTopic: usage_reports_v2
kafkaBroker: kafka:9092
kafkaBufferSize: 350
kafkaBufferInterval: 1000
kafkaBufferDynamic: 1

replicaCount: 1

sentry: 0
sentryDsn: ''

prometheusMetrics: 0
prometheusMetricsLabelInstance: ''
