global:
  image:
    tag: 59b64c36c866b3555c135c70de76a884e63f8619
  clickhouseUsername: default
  postgresql:
    auth:
      database: graphql-hive
      user: postgres
  apiKey:
    # -- list of API Keys to load and use with supertokens-core
    key: "yourApiKey"
  encryptionSecret: yourEncryptionSecret

image:
  name: ghcr.io/kamilkisiela/graphql-hive/server
  pullPolicy: Always

appName: hive-server
serverPort: 8080
nodeEnv: production

postgresHost: postgres-postgresql
postgresPort: 5432

roarrLog: true

clickhouseProtocol: http
clickhouseHost: clickhouse
clickhousePort: 8123

redisHost: redis-master
redisPort: 6379

tokensEndpoint: http://tokens-svc:80
webhooksEndpoint: http://webhooks-svc:80
schemaEndpoint: http://schema-svc:80
emailsEndpoint: http://emails-svc:80
webAppUrl: http://app-svc:80
supertokensConnectionUri: http://supertokens:3567

replicaCount: 1

rateLimitEndpoint: ''

integrationGithub: 0
integrationGithubGithubAppId: ''
integrationGithubGithubAppPrivateKey: ''

authOrganizationOidc: 0

sentry: 0
sentryDsn: ''

prometheusMetrics: 0
prometheusMetricsLabelInstance: ''
